name: Fire Toot workflow

on:
  workflow_dispatch:
  schedule:
     - cron: "30 * * * *"

jobs:
  toot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies 
        run: |-
          cd /home/runner/work/california_fire/california_fire
          pip install -r requirements.txt

      - name: Run tests
        run: |-
          cd /home/runner/work/california_fire/california_fire
          python -m unittest discover

      - name: Post fire title and map into Mastodon
        run: |-
          cd /home/runner/work/california_fire/california_fire
          python main.py
        env:
          MASTODON_EMAIL: ${{ secrets.MASTODON_EMAIL }}
          MASTODON_PASSWORD: ${{ secrets.MASTODON_PASSWORD }}
          MASTODON_SERVER: ${{ secrets.MASTODON_SERVER }}

      - name: Commit and push if api changed
        run: |-
          cd /home/runner/work/california_fire/california_fire/
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add outputs/old_fire.json
          timestamp=$(date -u)
          git commit -m "Latest response: ${timestamp}" || exit 0
          git push
